### ISSUE TITLE
Schema dumps

### ISSUE THREAD

**Issue by ExternalReality** [jtdaugherty/dbmigrations#11]
At least according to the Rails framework, it is not a good idea to depend on running every migration to completely update a databases schema from scratch. Would it be a good idea to have an option that would enable commands to dump the database schema (and the `installed migrations` relation) to a file after every migration? I would also implement a `moo schema-load` command to go  along with it.

**Comment by jtdaugherty** [comment]
To follow up on this after a long time:

At present, it would be possible to get what you want without any special support from `dbmigrations`.  Just run the schema dump tool of choice for your database, put the dump into revision control, and have the installation of that dump be the first thing you do before running any `moo` commands.  This will work because the dump will contain the migration metadata that `dbmigrations` uses to track installed migrations, so it will not try to install any migrations that are already in the database.

This approach works for new development systems while still giving you the ability to incrementally upgrade existing databases.  I'm going to close this under the assumption that this works for you, but please re-open if there's something more to be worked out!
