### ISSUE TITLE
Poor documentation with regard to set up

### ISSUE THREAD

**Issue by yaccz** [jtdaugherty/dbmigrations#16]
This things obviously needs some kind of configuration. That is supported by checking the help output of moo and presence of taking environment variables and a config file.

However, still unclear wheter there is default location where the config file is read from, what it's format is and what options are available. Generally what is the expected setup and workflow. A Getting started tutorial is needed.

**Comment by jtdaugherty** [comment]
The configuration file was a later addition, which may help explain why it isn't documented.  However, the configuration file is merely an alternative to the primary configuration mechanism that is documented in `MOO.TXT`.  Have you had a look at that file?

**Comment by yaccz** [comment]
Oh. I have looked at it briefly but it did not seem relevant to initial setup. Now I see there is "Before using moo, you must ...". However, it's under "moo: the dbmigrations management tool" section which is really non-descriptive.

First, I think that both readme and moo should be in better format than just text. They should be better organized. For example readme should point out moo.txt contains getting started thing. Then I don't see why moo.txt contains commands descriptions. The getting started part is only getting overlooked there. Besides, I expect these command descriptions be part of the --help output. The sole fact that there are commands descriptions in a text file makes me question their validity as these are bound to get obsolete, inacurate, etc and actually looking at the output of moo --help, they do seem at least out of sync.

Btw do you always set your env vars when you perform migrations? I'm thinking I should probably make a wrapper around this. You know, most db migration tools provide some kind of integration to the project in whose context they are being ran at. So you can specify your database connection once and be done with it. No passing of the path to config file via argv either. At least not for default location.

**Comment by yaccz** [comment]
Oh, I forgot to mention that readme and moo.txt  should be integrated into documentation built by haddock.

**Comment by jtdaugherty** [comment]
First off, I appreciate the reports of things that could be improved.

Second, I need you to know that I am more likely to address concrete, specific problems.  Many of the things you cited are judgments and I can't do anything with them because I don't know what you actually *want*.  We may or may not agree on "better formats" or the meaning of "better organized."  But either way, I want to know what will *help* you, not what is *wrong* with my package.

If you have strong feelings about how some of these things should be addressed -- and it sounds like you do -- then I would be happy to consider pull requests to fix them.  However, if you go that route, let's chat about the changes before you make them so I know what you have in mind.

As for your question about setting environment variables when performing migrations: that is *exactly* what the config file feature is for, although even without that, writing a shell script with those variables and sourcing it as part of your project environment is not very controversial.

**Comment by jtdaugherty** [comment]
Please check out the additions to `MOO.TXT` in https://github.com/jtdaugherty/dbmigrations/commit/3586185cb96061911edb12232c4054e202d5e162. There is now a "Getting started" section.

**Comment by jtdaugherty** [comment]
In a later commit, there is now a section on the configuration file format.

**Comment by jtdaugherty** [comment]
Have the changes I mentioned above address your main concerns?  If so, please close this ticket.  If not, consider closing this ticket and opening more specific ones.  Thanks!

**Comment by yaccz** [comment]
Yes, that's definetly an improvement. It's already been quite helpful to me. Thanks.

**Comment by jtdaugherty** [comment]
Wonderful!
