### ISSUE TITLE
Total encapsulation of migration information

### ISSUE THREAD

**Issue by 3noch** [jtdaugherty/dbmigrations#27]
Aside from Persistent's primitive migrations, this library comes the closest I've seen to my dream of building my application such that it is totally capable of doing migrations on its own. In other words, I don't want to deploy `moo` to my endpoints, but I want my web application to do migrations by itself.

I'd be interested in making this functionality more "first class" if you think it's worth it. At first glance, it seems that providing some TH functions to embed the preparsed YAML data could be sufficient.

**Comment by 3noch** [comment]
Of course, with a sufficiently complex deploy processes, this feature is not needed since you can (and often do) run the deploy from a different machine. But in some scenarios I have a very simple/primitive deploy process that could benefit from this.

**Comment by ocharles** [comment]
You already have access to `dbmigrations` as a library, perhaps what you want is to manually enumerate migrations in a directory and apply them in `main` yourself? That shouldn't be too hard.

**Comment by 3noch** [comment]
Yes, that's precisely it.

**Comment by jtdaugherty** [comment]
@3noch - Yes! I have always had the intention of making `dbmigrations` usable as a library as @ocharles pointed out, so I'm open to ways that use case could be improved and I wouldn't be surprised if it has rough edges because I have never used it that way myself except to write `moo`.  In fact I'd really like it if someone were to use it that way so we can spot issues. :)

As far as specific changes are concerned, I'm not sure what a TH embedding gets you that the current functionality doesn't.  Is it that you'd like to avoid dealing with Cabal package data files?  If that particular approach is really important to you, I would be interested in exploring whether it can be implemented in a separate add-on package.  Otherwise, if there are other library interface issues that are making the library developer-hostile, please feel free to open tickets for specific problems and we can get them addressed.

**Comment by 3noch** [comment]
The fact that you expose a library API is really awesome and it's one reason I'm excited to work with this tool. (Not to mention it appears to be the most fully-featured migration tool for Haskell.)

Using cabal data files would certainly be a good option for a library that includes migrations. For my use case, I don't even need a cabal package (other than the fact that it's the simplest way to build an app). I realize that it would be fairly straightforward to merely deploy my app along with the set of migration files it needs. However, since that set of migration files should be 100% static for that version of the application, I see no reason not to just embed them into the executable itself. That's why I was thinking of TH. Embedding them just makes the deployment process ridiculously easy since I can wrap my entire web application into a single file with no dependencies.

**Comment by ocharles** [comment]
For embedding like that then, you might want to consider [`hereFile`](https://hackage.haskell.org/package/here-1.2.7/docs/Data-String-Here-Uninterpolated.html).

**Comment by jtdaugherty** [comment]
@3noch - makes sense! If you have time and want to write a patch to make this easier, I'll merge it.

**Comment by jtdaugherty** [comment]
I'm going to close this due to inactivity; please feel free to re-open if this gets revived.
