### ISSUE TITLE
Document how to use dbmigrations programmatically.

### ISSUE THREAD

**Issue by amano-kenji** [jtdaugherty/dbmigrations#41]
I read README and MOO.TXT, but I still don't know how to use dbmigrations programmatically in my program.

moo is okay for development, but I want to use dbmigrations directly in production code.

Can you show me an example of automatic database upgrade for production code in README? The production code UI should just prompt a user for database upgrade. The production code should also create a SQLite file and initialize the database file completely.

**Comment by jtdaugherty** [comment]
Have you consulted the Haddock documentation [on Hackage](https://hackage.haskell.org/package/dbmigrations-2.1.0/docs/Database-Schema-Migrations.html)?

**Comment by amano-kenji** [comment]
I roughly figured out the entrie point for a simple automatic database bootstrap by reading haddock documentation on hackage. However, if there was a small README example that showed an entry point for the most common use case, understanding dbmigrations would be a lot faster.

**Comment by jtdaugherty** [comment]
It makes sense to me that a bit more introductory documentation would be helpful! I'm glad that you figured out some basics from the Haddock docs. I don't have plans to improve the docs but I'd be happy to consider patches to do so. Since this was overdue, I just added [a note](https://github.com/jtdaugherty/dbmigrations#stability-note) to the README about the maintenance status of this package.

**Comment by amano-kenji** [comment]
If you don't use dbmigrations, what do you use instead?

**Comment by jtdaugherty** [comment]
@amano-kenji I don't do any database programming in Haskell these days (and haven't for over a decade). So I don't have an alternative to recommend. The dbmigrations project came about at a time when I was learning Haskell and needing a database migration solution similar to ones I'd used in other programming languages at the time. I haven't looked at what else has been written in Haskell since I first wrote this library, but I wouldn't be surprised if there are very good options!

**Comment by amano-kenji** [comment]
There are haskell SQL libraries that come with typed database migrations.

While typed database migrations look cool for simple databases, they don't support advanced SQL features, and they must leave behind older versions of database tables as haskell types.

Imagine retaining lots of types for ancient versions of database tables in haskell code. I don't like that.

After researching various haskell database migration options, only dbmigrations was left. I may take up the maintenance if I use it.

Does dbmigrations just create the latest version of the database schema if there is nothing in a database? Or, does it have to bootstrap from the oldest database schema version to the latest?
